[api]
addr = "node4:8080"

[store]
memory = false
dataPath = "/tmp"

RaftId   = 4
RaftCluster = "http://node1:8081,http://node2:8082,http://node3:8083,http://node4:8084"
RaftJoin   = true
RaftPort = "node4:9904"